### ISSUE TITLE
"TypeError: transportCtor is not a constructor"

### ISSUE THREAD

**Issue by SjorsHijgenaar** [lcarli/NodeRedIoTHub#10]
Upon sending data to an IoT data hub I get the following error: 
> TypeError: transportCtor is not a constructor

The data is as follows:
`{"deviceId":"Device","key":"xxx","Protocol":"mqtt","Data":"{\"eVerbruik\":\"0\"}"}`

**Comment by BPYates** [comment]
@SjorsHijgenaar 
I have the same error... please can you let me know if you managed to resolve it?

**Comment by SjorsHijgenaar** [comment]
I used a different library: https://www.npmjs.com/package/node-red-contrib-azure-iot-hub I think it's that one. 

Met vriendelijke groet,
Sjors Hijgenaar

Verstuurd vanaf mijn iPhone

**Comment by rasavant-ms** [comment]
Hey @SjorsHijgenaar  and @BPYates - did this work for you?
Please let me know if you see this issue still and I could help out.

**Comment by Armin-FB** [comment]
@rasavant-ms I'm having this issue too. I used [this](https://github.com/Azure/azure-iot-sdk-node/tree/master/device/node-red) node before and it worked fine via connectrion string

**Comment by tinktonk** [comment]
I have aslo the same problem with this module.... Any news on this issue?

**Comment by SjorsHijgenaar** [comment]
what versions are you using?

**Comment by rasavant-ms** [comment]
This package has been modified with more features and bug fixes. Can you try now and let me know the result please?

**Comment by SjorsHijgenaar** [comment]
Latest version is working smoothly for me.

**Comment by rasavant-ms** [comment]
Great! closing out this issue. Feel free to re-open if you face any problems.
