### ISSUE TITLE
"azureiothub" node does not export "Hostname"

### ISSUE THREAD

**Issue by maniwilliams** [lcarli/NodeRedIoTHub#11]
I have set up node-red on my RaspberryPi to send some sensor data to my Azure IoT Hub. It worked fine when using the browser interface to enter the IoT Hub details. But I found when I try to export the flow to deploy it to another device, "Hostname" field was not included. I have to open the node-red in a browser and manually type it.

Is this a security measure?

**Comment by nevekkeven** [comment]
It's not a bug, the hostname is not exportable.

**Comment by rasavant-ms** [comment]
Hey @maniwilliams, the comment by @nevekkeven is valid and gets a thumbsup.
Closing this issue. Please reach out again if needed!
