### ISSUE TITLE
C2D Received data

### ISSUE THREAD

**Issue by Gadnief** [lcarli/NodeRedIoTHub#12]
I managed to receive some data that i created in a azure function and sent back to the iot hub. When i place a debug node behind the IoT Hub node it shows me just the information: "[object Object]". How can i read the data i received (i wanna print the results on a senseHat)? Thanks for the help!

**Comment by lcarli** [comment]
Convert to JSON

**Comment by rasavant-ms** [comment]
Hey @Gadnief, I hope you were able to print/read the data received by converting it to JSON !
Closing this issue, but feel free to reach out again.
