### ISSUE TITLE
Connection String Error

### ISSUE THREAD

**Issue by ProgrammingPescador** [lcarli/NodeRedIoTHub#14]
Hi

I have just installed the latest Nod Red and Azure IoT hub nodes on my raspberry pi.  The connection string property of the hub node is not saving.  I have tried with all protocols and cannot get the connection string to save so I am unable to connect to my hub.

Are there any workarounds for this?

Thanks
David Dwyer

**Comment by rasavant-ms** [comment]
Hello @ProgrammingPescador, 
is there any way you could share screen shots of the error that you see?
Do you mean the connectionString property of the Azure IoT Hub Registry?
Which browser are you using on your Pi?

**Comment by ProgrammingPescador** [comment]
Hi

Thanks for the response, I had to give up with the evaluation and move on to other business critical issues.

If I remember correctly the Node was not storing the IoT hub connection string in its property page.  I was not using the browser on the Pi I was using Chrome on my Windows PC connected to the Node Red server on the Pi.

I doubt I am going to get to look at this for a while as it has been so long since the original work and we have moved on to other projects.  If you are able to let me know if this has been fixed or will be I will put it back on my list of jobs

Regards

**Comment by rasavant-ms** [comment]
There was a new version for this package released last week. Feel free to re-open this issue if you face a problem with the latest version.
The best way to update your node-RED to use the latest package is to run the following command first:
update-nodejs-and-nodered

I am closing this issue now.
