### ISSUE TITLE
Flows stopped due to missimg node types

### ISSUE THREAD

**Issue by rhoddan** [lcarli/NodeRedIoTHub#21]
Why does I get this error with a fresh and updated raspian stretch?

![dd1dfc46-25f8-41d9-af51-16976c55fb6e](https://user-images.githubusercontent.com/33499995/37623737-03765064-2bc6-11e8-8b2a-7cb2d173fd43.jpeg)

**Comment by rasavant-ms** [comment]
Hello @rhoddan, 
There has been a new version update for the node-red-contrib-azure-iot-hub package.
I would recommend running this command in your .node-red directory before kicking off node-red:
npm init

Let me know if you still face any problems

**Comment by rhoddan** [comment]
I tried the command npm init and just press enter, enter enter ...
Still same problem 
![3ddd1b91-6c4e-45f7-8924-0557af592efc](https://user-images.githubusercontent.com/33499995/37624547-d1c05f3a-2bc8-11e8-99b2-bd076e81f781.jpeg)

**Comment by rhoddan** [comment]
I think the trick was: update-nodejs-and-nodered
