### ISSUE TITLE
SyntaxError: Unexpected token [

### ISSUE THREAD

**Issue by roqvist** [lcarli/NodeRedIoTHub#3]
I get the following error message:

    [error] [azureiothub:Azure IoT Hub] SyntaxError: Unexpected token [

Tried both `mqtt` and `amqp` protocols and different `data` values, basic strings and JSON objects.

**Comment by rasavant-ms** [comment]
Hey @roqvist,

Do you still see this issue? I could help out if you can provide a couple of more details:
What is your flow like?
What is the payload and Azure Iot Hub node properties that you are using?

**Comment by rasavant-ms** [comment]
Please try updating the package using the below command:
update-nodejs-and-nodered

I am closing this issue now. Feel free to re-open if you face any problems.
