### ISSUE TITLE
Connection String Error

### ISSUE THREAD

**Issue by retom** [lcarli/NodeRedIoTHub#5]
Hi 
getting  this error:
5.3.2017, 12:16:49node: Azure IoT Hub
msg : error "ArgumentError: The connection string is missing the property: DeviceId"

My String in the node is: 
HostName=XXXXXXXXX.azure-devices.net;SharedAccessKeyName=iothubowner;SharedAccessKey=XXXXXXXXX
What shall i change?

Thank you!
reto

**Comment by rasavant-ms** [comment]
Is this is the string in your payload?
Your payload should look like this:
{
    "deviceId": "device146",
    "key": "XXXXXXX",
    "protocol": "http",
    "data": "{tem: 25, wind: 20}"
}

Let me know if this does not work.

**Comment by rasavant-ms** [comment]
Closing out this issue. Feel free to reopen if you find any issues with the newer version of this package.
Use this command to update:
update-nodejs-and-nodered
