### ISSUE TITLE
Wrong data sent to IoT Hub

### ISSUE THREAD

**Issue by beneuto** [lcarli/NodeRedIoTHub#6]
I have 2 node-red tabs sending data to IoT Hub under different device IDs.   The first tab runs every minute to query data from the source and pass into IoT Hub using MQTT.   The second tab uses a streamed source that updates around every 15 minutes.
The issue is that when the second tab fires, the data getting sent to Azure IoT Hub is that from the first tab but it is recorded under the Device ID as per the second tab connection.   
Debug on the output of the node feeding the IoT Hub node shows the correct data is sent to the node, however that data never makes it to the IoT Hub.
Changing the 2nd tab node to AMQP (with the 1st remaining on MQTT) makes no difference.

**Comment by rasavant-ms** [comment]
Hey @beneuto, 

To be able to help you better, would you provide me with the following details:
1. How is your flow like? Can you provide a verbal representation of it? Eg. inject -> azureiothub -> log
2. What are the payloads and/or node properties for each flow?

I am guessing that maybe the payload message being sent to the Hub could be an issue here.

**Comment by beneuto** [comment]
I think this was already fixed (in a dependency perhaps?).   Regardless, I am using this node extensively without a problem so this issue can be closed.

**Comment by rasavant-ms** [comment]
Great, thanks! I will close this out.
