### ISSUE TITLE
node.log is not a function

### ISSUE THREAD

**Issue by mariocytr** [lcarli/NodeRedIoTHub#8]
"TypeError: node.log is not a function" thrown when running the example from readme.txt

**Comment by nevekkeven** [comment]
I have the same error when I connect to Azure, I turn off my wifi and I try to send a data to azure.

Edit : 
This pull request fix the issue https://github.com/lcarli/NodeRedIoTHub/pull/7

**Comment by rasavant-ms** [comment]
Thanks for fixing this @nevekkeven !
I am closing this issue.
